### Синтаксис Numpy

In [1]:
import numpy as np

#### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
N = 10
np.arange(N - 1, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
N = 10
diag_N = np.diag(np.arange(N - 1, -1, -1), k = 0)
print(diag_N)
print(diag_N.ravel().sum())

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
45


#### Задание 3
Решите систему уравнений:<br>
4x + 2y + z = 4<br>
x + 3y = 12<br>
5y + 4z = -3<br>

In [4]:
left = np.array([ [4, 2, 1], [1, 3, 0], [0, 5, 4] ])
right = np.array([4, 12, -3])

from numpy import linalg
solution = linalg.solve(left, right)

print('Верно') if np.allclose(np.dot(left, solution), right) else print('Неверно') # проверить правильное решение

fake_solution = np.array([ 0.46666667, 3.84444444, -5])
print('Верно') if np.allclose(np.dot(left, fake_solution), right) else print('Неверно')  # проверить неправильное решение

print(f'Решение системы: {solution}')

Верно
Неверно
Решение системы: [ 0.46666667  3.84444444 -5.55555556]


#### Задание 4
Имеется матрица покупок в интернет-магазине. Строки - ID пользователя (нумерация начинается с 1 и по порядку). Cтолбцы - количество покупок категорий товаров этим пользователем. На сайт заходит очередной посетитель, найдите самого похожего на него пользователя, т.е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats.

In [5]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
                            ], np.int32)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [6]:
def cosine( a, b ):
    '''Функция, вычисляющая косинусное сходство по координатам векторов'''
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )    
    return np.dot( a, b ) / ( aLength * bLength )

##### Вариант 1 (просто вывод)

In [7]:
cosine_max = 0
max_id = 0

for i,el in enumerate(users_stats):
    if cosine(el, next_user_stats) > cosine_max:
        cosine_max = cosine(el, next_user_stats)
        max_id = i + 1                            
print(f'Максимальное сходство: {cosine_max: .4f}, id: {max_id}')    

Максимальное сходство:  0.9487, id: 8


##### Вариант 2 (словарь)

In [8]:
cosine_dict = {}

for i,el in enumerate(users_stats):
    cosine_dict[i + 1] = round(cosine(el, next_user_stats), 4)
    
max(cosine_dict.items(), key = lambda x: x[1])

(8, 0.9487)

##### Вариант 3 (массив)

In [9]:
cosine_array = np.array( [] )

for i,el in enumerate(users_stats):
    cosine_array = np.append(cosine_array, cosine(el, next_user_stats))
    
print(f'Максимальное сходство: {np.amax(cosine_array): .4f}')
print(f'Самый похожий пользователь с id: {np.argmax(cosine_array) + 1}')

Максимальное сходство:  0.9487
Самый похожий пользователь с id: 8
